// Generated by gencpp from file publisher_pkg/myRandomRequest.msg
// DO NOT EDIT!


#ifndef PUBLISHER_PKG_MESSAGE_MYRANDOMREQUEST_H
#define PUBLISHER_PKG_MESSAGE_MYRANDOMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace publisher_pkg
{
template <class ContainerAllocator>
struct myRandomRequest_
{
  typedef myRandomRequest_<ContainerAllocator> Type;

  myRandomRequest_()
    : random_num(0.0)  {
    }
  myRandomRequest_(const ContainerAllocator& _alloc)
    : random_num(0.0)  {
  (void)_alloc;
    }



   typedef float _random_num_type;
  _random_num_type random_num;





  typedef boost::shared_ptr< ::publisher_pkg::myRandomRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::publisher_pkg::myRandomRequest_<ContainerAllocator> const> ConstPtr;

}; // struct myRandomRequest_

typedef ::publisher_pkg::myRandomRequest_<std::allocator<void> > myRandomRequest;

typedef boost::shared_ptr< ::publisher_pkg::myRandomRequest > myRandomRequestPtr;
typedef boost::shared_ptr< ::publisher_pkg::myRandomRequest const> myRandomRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::publisher_pkg::myRandomRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::publisher_pkg::myRandomRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::publisher_pkg::myRandomRequest_<ContainerAllocator1> & lhs, const ::publisher_pkg::myRandomRequest_<ContainerAllocator2> & rhs)
{
  return lhs.random_num == rhs.random_num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::publisher_pkg::myRandomRequest_<ContainerAllocator1> & lhs, const ::publisher_pkg::myRandomRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace publisher_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::publisher_pkg::myRandomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::publisher_pkg::myRandomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::publisher_pkg::myRandomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::publisher_pkg::myRandomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::publisher_pkg::myRandomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::publisher_pkg::myRandomRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::publisher_pkg::myRandomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4176a749b1704bf728d01e1708640142";
  }

  static const char* value(const ::publisher_pkg::myRandomRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4176a749b1704bf7ULL;
  static const uint64_t static_value2 = 0x28d01e1708640142ULL;
};

template<class ContainerAllocator>
struct DataType< ::publisher_pkg::myRandomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "publisher_pkg/myRandomRequest";
  }

  static const char* value(const ::publisher_pkg::myRandomRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::publisher_pkg::myRandomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 random_num\n"
;
  }

  static const char* value(const ::publisher_pkg::myRandomRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::publisher_pkg::myRandomRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.random_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myRandomRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::publisher_pkg::myRandomRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::publisher_pkg::myRandomRequest_<ContainerAllocator>& v)
  {
    s << indent << "random_num: ";
    Printer<float>::stream(s, indent + "  ", v.random_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUBLISHER_PKG_MESSAGE_MYRANDOMREQUEST_H
