// Generated by gencpp from file publisher_pkg/myRandom.msg
// DO NOT EDIT!


#ifndef PUBLISHER_PKG_MESSAGE_MYRANDOM_H
#define PUBLISHER_PKG_MESSAGE_MYRANDOM_H

#include <ros/service_traits.h>


#include <publisher_pkg/myRandomRequest.h>
#include <publisher_pkg/myRandomResponse.h>


namespace publisher_pkg
{

struct myRandom
{

typedef myRandomRequest Request;
typedef myRandomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct myRandom
} // namespace publisher_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::publisher_pkg::myRandom > {
  static const char* value()
  {
    return "af3f1147d7daae631b82b1a427cd4a2f";
  }

  static const char* value(const ::publisher_pkg::myRandom&) { return value(); }
};

template<>
struct DataType< ::publisher_pkg::myRandom > {
  static const char* value()
  {
    return "publisher_pkg/myRandom";
  }

  static const char* value(const ::publisher_pkg::myRandom&) { return value(); }
};


// service_traits::MD5Sum< ::publisher_pkg::myRandomRequest> should match
// service_traits::MD5Sum< ::publisher_pkg::myRandom >
template<>
struct MD5Sum< ::publisher_pkg::myRandomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::publisher_pkg::myRandom >::value();
  }
  static const char* value(const ::publisher_pkg::myRandomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::publisher_pkg::myRandomRequest> should match
// service_traits::DataType< ::publisher_pkg::myRandom >
template<>
struct DataType< ::publisher_pkg::myRandomRequest>
{
  static const char* value()
  {
    return DataType< ::publisher_pkg::myRandom >::value();
  }
  static const char* value(const ::publisher_pkg::myRandomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::publisher_pkg::myRandomResponse> should match
// service_traits::MD5Sum< ::publisher_pkg::myRandom >
template<>
struct MD5Sum< ::publisher_pkg::myRandomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::publisher_pkg::myRandom >::value();
  }
  static const char* value(const ::publisher_pkg::myRandomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::publisher_pkg::myRandomResponse> should match
// service_traits::DataType< ::publisher_pkg::myRandom >
template<>
struct DataType< ::publisher_pkg::myRandomResponse>
{
  static const char* value()
  {
    return DataType< ::publisher_pkg::myRandom >::value();
  }
  static const char* value(const ::publisher_pkg::myRandomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PUBLISHER_PKG_MESSAGE_MYRANDOM_H
