// Generated by gencpp from file publisher_pkg/myRandomResponse.msg
// DO NOT EDIT!


#ifndef PUBLISHER_PKG_MESSAGE_MYRANDOMRESPONSE_H
#define PUBLISHER_PKG_MESSAGE_MYRANDOMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace publisher_pkg
{
template <class ContainerAllocator>
struct myRandomResponse_
{
  typedef myRandomResponse_<ContainerAllocator> Type;

  myRandomResponse_()
    : judge(false)  {
    }
  myRandomResponse_(const ContainerAllocator& _alloc)
    : judge(false)  {
  (void)_alloc;
    }



   typedef uint8_t _judge_type;
  _judge_type judge;





  typedef boost::shared_ptr< ::publisher_pkg::myRandomResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::publisher_pkg::myRandomResponse_<ContainerAllocator> const> ConstPtr;

}; // struct myRandomResponse_

typedef ::publisher_pkg::myRandomResponse_<std::allocator<void> > myRandomResponse;

typedef boost::shared_ptr< ::publisher_pkg::myRandomResponse > myRandomResponsePtr;
typedef boost::shared_ptr< ::publisher_pkg::myRandomResponse const> myRandomResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::publisher_pkg::myRandomResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::publisher_pkg::myRandomResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::publisher_pkg::myRandomResponse_<ContainerAllocator1> & lhs, const ::publisher_pkg::myRandomResponse_<ContainerAllocator2> & rhs)
{
  return lhs.judge == rhs.judge;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::publisher_pkg::myRandomResponse_<ContainerAllocator1> & lhs, const ::publisher_pkg::myRandomResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace publisher_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::publisher_pkg::myRandomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::publisher_pkg::myRandomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::publisher_pkg::myRandomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::publisher_pkg::myRandomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::publisher_pkg::myRandomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::publisher_pkg::myRandomResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::publisher_pkg::myRandomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39c17c8a5cd9af966a5aecabf6af7bef";
  }

  static const char* value(const ::publisher_pkg::myRandomResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39c17c8a5cd9af96ULL;
  static const uint64_t static_value2 = 0x6a5aecabf6af7befULL;
};

template<class ContainerAllocator>
struct DataType< ::publisher_pkg::myRandomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "publisher_pkg/myRandomResponse";
  }

  static const char* value(const ::publisher_pkg::myRandomResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::publisher_pkg::myRandomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool judge\n"
;
  }

  static const char* value(const ::publisher_pkg::myRandomResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::publisher_pkg::myRandomResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.judge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myRandomResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::publisher_pkg::myRandomResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::publisher_pkg::myRandomResponse_<ContainerAllocator>& v)
  {
    s << indent << "judge: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.judge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUBLISHER_PKG_MESSAGE_MYRANDOMRESPONSE_H
