// Generated by gencpp from file publisher_pkg/theRandomNum.msg
// DO NOT EDIT!


#ifndef PUBLISHER_PKG_MESSAGE_THERANDOMNUM_H
#define PUBLISHER_PKG_MESSAGE_THERANDOMNUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace publisher_pkg
{
template <class ContainerAllocator>
struct theRandomNum_
{
  typedef theRandomNum_<ContainerAllocator> Type;

  theRandomNum_()
    : data(0.0)  {
    }
  theRandomNum_(const ContainerAllocator& _alloc)
    : data(0.0)  {
  (void)_alloc;
    }



   typedef float _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::publisher_pkg::theRandomNum_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::publisher_pkg::theRandomNum_<ContainerAllocator> const> ConstPtr;

}; // struct theRandomNum_

typedef ::publisher_pkg::theRandomNum_<std::allocator<void> > theRandomNum;

typedef boost::shared_ptr< ::publisher_pkg::theRandomNum > theRandomNumPtr;
typedef boost::shared_ptr< ::publisher_pkg::theRandomNum const> theRandomNumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::publisher_pkg::theRandomNum_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::publisher_pkg::theRandomNum_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::publisher_pkg::theRandomNum_<ContainerAllocator1> & lhs, const ::publisher_pkg::theRandomNum_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::publisher_pkg::theRandomNum_<ContainerAllocator1> & lhs, const ::publisher_pkg::theRandomNum_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace publisher_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::publisher_pkg::theRandomNum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::publisher_pkg::theRandomNum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::publisher_pkg::theRandomNum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::publisher_pkg::theRandomNum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::publisher_pkg::theRandomNum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::publisher_pkg::theRandomNum_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::publisher_pkg::theRandomNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73fcbf46b49191e672908e50842a83d4";
  }

  static const char* value(const ::publisher_pkg::theRandomNum_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73fcbf46b49191e6ULL;
  static const uint64_t static_value2 = 0x72908e50842a83d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::publisher_pkg::theRandomNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "publisher_pkg/theRandomNum";
  }

  static const char* value(const ::publisher_pkg::theRandomNum_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::publisher_pkg::theRandomNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 data\n"
;
  }

  static const char* value(const ::publisher_pkg::theRandomNum_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::publisher_pkg::theRandomNum_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct theRandomNum_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::publisher_pkg::theRandomNum_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::publisher_pkg::theRandomNum_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<float>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUBLISHER_PKG_MESSAGE_THERANDOMNUM_H
