// Generated by gencpp from file service_pkg/numberResponse.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_NUMBERRESPONSE_H
#define SERVICE_PKG_MESSAGE_NUMBERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_pkg
{
template <class ContainerAllocator>
struct numberResponse_
{
  typedef numberResponse_<ContainerAllocator> Type;

  numberResponse_()
    : feedback(false)  {
    }
  numberResponse_(const ContainerAllocator& _alloc)
    : feedback(false)  {
  (void)_alloc;
    }



   typedef uint8_t _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::service_pkg::numberResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_pkg::numberResponse_<ContainerAllocator> const> ConstPtr;

}; // struct numberResponse_

typedef ::service_pkg::numberResponse_<std::allocator<void> > numberResponse;

typedef boost::shared_ptr< ::service_pkg::numberResponse > numberResponsePtr;
typedef boost::shared_ptr< ::service_pkg::numberResponse const> numberResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_pkg::numberResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_pkg::numberResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_pkg::numberResponse_<ContainerAllocator1> & lhs, const ::service_pkg::numberResponse_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_pkg::numberResponse_<ContainerAllocator1> & lhs, const ::service_pkg::numberResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::numberResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::numberResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_pkg::numberResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_pkg::numberResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::numberResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::numberResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_pkg::numberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1f168a39479bedb24dba7a087426182";
  }

  static const char* value(const ::service_pkg::numberResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1f168a39479bedbULL;
  static const uint64_t static_value2 = 0x24dba7a087426182ULL;
};

template<class ContainerAllocator>
struct DataType< ::service_pkg::numberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_pkg/numberResponse";
  }

  static const char* value(const ::service_pkg::numberResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_pkg::numberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool feedback\n"
"\n"
;
  }

  static const char* value(const ::service_pkg::numberResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_pkg::numberResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct numberResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_pkg::numberResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_pkg::numberResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_NUMBERRESPONSE_H
