// Generated by gencpp from file service_pkg/numberRequest.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_NUMBERREQUEST_H
#define SERVICE_PKG_MESSAGE_NUMBERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_pkg
{
template <class ContainerAllocator>
struct numberRequest_
{
  typedef numberRequest_<ContainerAllocator> Type;

  numberRequest_()
    : number(0.0)  {
    }
  numberRequest_(const ContainerAllocator& _alloc)
    : number(0.0)  {
  (void)_alloc;
    }



   typedef float _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::service_pkg::numberRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_pkg::numberRequest_<ContainerAllocator> const> ConstPtr;

}; // struct numberRequest_

typedef ::service_pkg::numberRequest_<std::allocator<void> > numberRequest;

typedef boost::shared_ptr< ::service_pkg::numberRequest > numberRequestPtr;
typedef boost::shared_ptr< ::service_pkg::numberRequest const> numberRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_pkg::numberRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_pkg::numberRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_pkg::numberRequest_<ContainerAllocator1> & lhs, const ::service_pkg::numberRequest_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_pkg::numberRequest_<ContainerAllocator1> & lhs, const ::service_pkg::numberRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::numberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::numberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_pkg::numberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_pkg::numberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::numberRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::numberRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_pkg::numberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ded049c24c756963282afab14b2d0f6d";
  }

  static const char* value(const ::service_pkg::numberRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xded049c24c756963ULL;
  static const uint64_t static_value2 = 0x282afab14b2d0f6dULL;
};

template<class ContainerAllocator>
struct DataType< ::service_pkg::numberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_pkg/numberRequest";
  }

  static const char* value(const ::service_pkg::numberRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_pkg::numberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 number\n"
;
  }

  static const char* value(const ::service_pkg::numberRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_pkg::numberRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct numberRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_pkg::numberRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_pkg::numberRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<float>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_NUMBERREQUEST_H
