// Generated by gencpp from file service_pkg/number.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_NUMBER_H
#define SERVICE_PKG_MESSAGE_NUMBER_H

#include <ros/service_traits.h>


#include <service_pkg/numberRequest.h>
#include <service_pkg/numberResponse.h>


namespace service_pkg
{

struct number
{

typedef numberRequest Request;
typedef numberResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct number
} // namespace service_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_pkg::number > {
  static const char* value()
  {
    return "856707387f0b62b7754ee4f39be9c0f3";
  }

  static const char* value(const ::service_pkg::number&) { return value(); }
};

template<>
struct DataType< ::service_pkg::number > {
  static const char* value()
  {
    return "service_pkg/number";
  }

  static const char* value(const ::service_pkg::number&) { return value(); }
};


// service_traits::MD5Sum< ::service_pkg::numberRequest> should match
// service_traits::MD5Sum< ::service_pkg::number >
template<>
struct MD5Sum< ::service_pkg::numberRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::number >::value();
  }
  static const char* value(const ::service_pkg::numberRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::numberRequest> should match
// service_traits::DataType< ::service_pkg::number >
template<>
struct DataType< ::service_pkg::numberRequest>
{
  static const char* value()
  {
    return DataType< ::service_pkg::number >::value();
  }
  static const char* value(const ::service_pkg::numberRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_pkg::numberResponse> should match
// service_traits::MD5Sum< ::service_pkg::number >
template<>
struct MD5Sum< ::service_pkg::numberResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::number >::value();
  }
  static const char* value(const ::service_pkg::numberResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::numberResponse> should match
// service_traits::DataType< ::service_pkg::number >
template<>
struct DataType< ::service_pkg::numberResponse>
{
  static const char* value()
  {
    return DataType< ::service_pkg::number >::value();
  }
  static const char* value(const ::service_pkg::numberResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_NUMBER_H
