// Generated by gencpp from file topic_pkg/range.msg
// DO NOT EDIT!


#ifndef TOPIC_PKG_MESSAGE_RANGE_H
#define TOPIC_PKG_MESSAGE_RANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace topic_pkg
{
template <class ContainerAllocator>
struct range_
{
  typedef range_<ContainerAllocator> Type;

  range_()
    : number(0)  {
    }
  range_(const ContainerAllocator& _alloc)
    : number(0)  {
  (void)_alloc;
    }



   typedef int16_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::topic_pkg::range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topic_pkg::range_<ContainerAllocator> const> ConstPtr;

}; // struct range_

typedef ::topic_pkg::range_<std::allocator<void> > range;

typedef boost::shared_ptr< ::topic_pkg::range > rangePtr;
typedef boost::shared_ptr< ::topic_pkg::range const> rangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topic_pkg::range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topic_pkg::range_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::topic_pkg::range_<ContainerAllocator1> & lhs, const ::topic_pkg::range_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::topic_pkg::range_<ContainerAllocator1> & lhs, const ::topic_pkg::range_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace topic_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::topic_pkg::range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topic_pkg::range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topic_pkg::range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topic_pkg::range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic_pkg::range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic_pkg::range_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topic_pkg::range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6500e1e658110ec1daa9475082592be3";
  }

  static const char* value(const ::topic_pkg::range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6500e1e658110ec1ULL;
  static const uint64_t static_value2 = 0xdaa9475082592be3ULL;
};

template<class ContainerAllocator>
struct DataType< ::topic_pkg::range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topic_pkg/range";
  }

  static const char* value(const ::topic_pkg::range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topic_pkg::range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 number\n"
;
  }

  static const char* value(const ::topic_pkg::range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topic_pkg::range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topic_pkg::range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::topic_pkg::range_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int16_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOPIC_PKG_MESSAGE_RANGE_H
