test:test.o Longest_Palindrome.o
	g++ test.o Longest_Palindrome.o -o test
Longest_Palindrome.o:Longest_Palindrome.h Longest_Palindrome.cpp
	g++ -c Longest_Palindrome.cpp -o Longest_Palindrome.o
test.o:test.cpp
	g++ -c test.cpp -o test.o
